discord_application_token = ""
guild_veify_channel_id = 
guild_veified_role_id = 
guild_global_role_id = 
guild_room_category_id = 
verify_message_id = 
verified_role_id = 
reaction_role_age_message_id = 
age_roles_id = []
reaction_role_dm_status_message_id = 
dm_status_roles_id = []
